# Generated by Django 3.2.3 on 2021-05-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('received', models.DateTimeField(blank=True, default=None, null=True, verbose_name='received')),
                ('visibility', models.CharField(choices=[('anonimous', "I don't want identify myself"), ('public', 'I want indentify myself')], default='public', max_length=255, verbose_name='visibility')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('district', models.CharField(blank=True, max_length=255, verbose_name='district')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], default='', max_length=255, verbose_name='gender')),
                ('age_group', models.CharField(blank=True, choices=[('up to 18 years', 'até 18 anos'), ('18 to 24 years', '18 a 24 anos'), ('25 to 34 years', '25 a 34 anos'), ('35 to 44 years', '35 a 44 anos'), ('45 to 54 years', '45 a 54 anos'), ('55 to 64 years', '55 a 64 anos'), ('more than 65 years', 'mais de 65 anos')], max_length=255, verbose_name='age group')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('protocol', models.CharField(blank=True, max_length=255, verbose_name='protocol')),
                ('message', models.TextField(verbose_name='message')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email')),
                ('assigned', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='assigned')),
                ('answer', models.TextField(blank=True, verbose_name='answer')),
                ('answer_file', models.FileField(blank=True, upload_to='ombudsman/answer/', verbose_name='answer file')),
                ('answer_file_label', models.CharField(blank=True, max_length=255, verbose_name='answer file label')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entrys',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='EntrySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Entry Source',
                'verbose_name_plural': 'Entrys Source',
            },
        ),
        migrations.CreateModel(
            name='EntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Entry Status',
                'verbose_name_plural': 'Entrys Status',
            },
        ),
        migrations.CreateModel(
            name='EntryTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Entry Topic',
                'verbose_name_plural': 'Entrys Topic',
            },
        ),
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='color')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Entry Type',
                'verbose_name_plural': 'Entrys Type',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attachment', models.FileField(blank=True, upload_to='ombudsman/interaction/', verbose_name='attachment')),
                ('internal_memo', models.TextField(verbose_name='internal memo')),
                ('public_memo', models.TextField(verbose_name='public memo')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombudsman.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombudsman.entrytype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ombudsman.entrysource', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ombudsman.entrystatus', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ombudsman.entrytopic', verbose_name='topic'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('archive', models.FileField(upload_to='ombudsman/entry/', verbose_name='archive')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ombudsman.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
