# Generated by Django 3.2.3 on 2021-05-23 05:42

import cpf_field.models
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ombudsman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='cpf',
            field=cpf_field.models.CPFField(default=None, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, verbose_name='phone'),
        ),
    ]
