# Generated by Django 3.2.3 on 2021-05-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombudsman', '0002_auto_20210523_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='age_group',
            field=models.CharField(blank=True, choices=[('up to 18 years', 'até 18 anos'), ('18 to 24 years', '18 a 24 anos'), ('25 to 34 years', '25 a 34 anos'), ('35 to 44 years', '35 a 44 anos'), ('45 to 54 years', '45 a 54 anos'), ('55 to 64 years', '55 a 64 anos'), ('more than 65 years', 'mais de 65 anos')], max_length=255, null=True, verbose_name='age group'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='gender',
            field=models.CharField(blank=True, choices=[('not-answer', 'Not answer'), ('female', 'Female'), ('male', 'Male')], default='', max_length=255, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
