# Generated by Django 3.2.3 on 2021-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombudsman', '0003_auto_20210523_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='action',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='action'),
        ),
    ]
